= Version 0.11.0

_Release Name:_ Inji Web 0.11.0

_Support:_ Developer

_Release Date:_ 29th Jan, 2025

=== _Overview_

This release introduces several enhancements, new features, aimed at improving the functionality, security, and user experience of the platform. Key objectives include secure time-bound storage, and UI updates to align with new branding standards.

=== _Major Highlights/Features_

_ _Secure Time-Bound Storage*: Introduced functionality to set validity periods for credentials before download, ensuring secure and controlled access to stored data.
_ _VC Verification During Download*:
  _ _RSA VC Verification*: For verifying RSA-based Verifiable Credentials before download within the Inji Web Wallet.
  _ _EdDSA VC Verification*: Integrated VC Verifier SDK to enable seamless verification of EdDSA-based Verifiable Credentials during downloads.
_ _Mimoto Enhancements and Additions*
  * Trusted Verifiers API - Introduced the Trusted Verifiers API to enhance the verification process and enable secure interaction with trusted verifiers.
  _ Main Branch Renamed - The “_Main branch_” in the Mimoto repository has been renamed to “_Master Branch”* for consistency and improved repository management.
  * mDoc VC Format Support - Added support for the mDoc Verifiable Credential (VC) format, allowing seamless integration and verification of mdoc credentials.
  _ _Compatibility and Availability*
    _ These enhancements are currently available for testing and building using the _Inji Mobile Wallet*.
    _ Support for _Inji Web* will be introduced in upcoming releases.
    _ Fully compatible with _Inji Mobile Wallet v0.15.0 onwards*, which is part of the ongoing release pipeline.

=== _Enhancements_

_Security Fixes_

* All critical security issues addressed and resolved.
* Sonar issues fixed, with the Sonar report.

_UI Enhancements_

_ _Inji Web Wallet Home Page*:
  * Incorporated new branding changes for a modern and enhanced user experience.
  * Ensured a fully responsive design for seamless access across devices.
  * Implemented a comprehensive FAQ section for an improved and readily available answers to frequently asked questions.

=== _Bugs Fixes_

Below is the [_list_](https://mosip.atlassian.net/issues/INJIWEB-1024?jql=project%20%3D%20%22Inji%20Web%22%20AND%20fixversion%20IN%20%281.0.0%2C%200.11.0%29%20AND%20type%20%3D%20Bug%20ORDER%20BY%20created%20DESC) of fixes as part of the _0.11.0_ release:

<table><thead><tr><th width="230">Jira issue</th><th>Issue description</th></tr></thead><tbody><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1000"><strong>Inji Web-1000</strong></a></td><td>Inji Web: Could not open help and About Inji pages in mobile phone</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1024"><strong>Inji Web-1024</strong></a></td><td>Inji Web: zerotimes and maximum limit(1000000000) are not properly handled while downloading the VC</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1001"><strong>Inji Web-1001</strong></a></td><td>Inji Web: Overlapping observed for credentials when opened in mobile phone</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-966"><strong>Inji Web-966</strong></a></td><td>Inji Web: For Hindi full stop observed like "।" and also "." in FAQ page</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-965"><strong>Inji Web-965</strong></a></td><td>Inji Web: In some languages in the last FAQ Online Sharing translating to selected lang but not the Embedded VC</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-876"><strong>Inji Web-876</strong></a></td><td>Inji Web: Intermediately We are not able to download the Sunbird VC in Inji Web</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-762"><strong>Inji Web-762</strong></a></td><td>Inji Web: Error description is not proper when the record is not available in durian</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-761"><strong>Inji Web-761</strong></a></td><td>Inji Web: Cientid is different and redirect URI are from different domains</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-661"><strong>Inji Web-661</strong></a></td><td>Security testing: Inji web - DEBUG mode is set in mosip-config</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-657"><strong>Inji Web-657</strong></a></td><td>Security testing: Inji web UI landing page is not fully visible, the footer blocks the view of partners</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-655"><strong>Inji Web-655</strong></a></td><td>Security testing: Inji web - blank page error response during URL tampering</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-651"><strong>Inji Web-651</strong></a></td><td>snyk dependency analysis: Inji web (develop)</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-650"><strong>Inji Web-650</strong></a></td><td>Security hotspot on Inji Web: develop branch</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-625"><strong>Inji Web-625</strong></a></td><td>Inji - QR code generated in Inji Web and in Inji Mobile are not matching</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-599"><strong>Inji Web-599</strong></a></td><td>Inji Web: Getting invalid credentials error message for valid data, when we leave authentication page idle for sometime</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-290"><strong>Inji Web-290</strong></a></td><td>Inji Web: QR code is not working on VC card</td></tr></tbody></table>

=== _Known Open Bugs_

Below is the list of _known_ issues. To read in detail click [_here_](https://mosip.atlassian.net/issues/?jql=project%3D%22Inji%20Web%22%20and%20type%20in%20%28bug%29%20and%20status%20not%20in%20%28closed%2C%20canceled%29%20order%20by%20created%20DESC)_._

<table><thead><tr><th width="229">Jira ID</th><th>Description</th></tr></thead><tbody><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-625"><strong>Inji Web-625</strong></a></td><td>Inji - QR code generated in Inji Web and in Inji Mobile are not matching.</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1148"><strong>Inji Web-1148</strong></a></td><td>Inji Web: In Arabic lang, consent option strings and buttons are overlapping in tablet portrait mode</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1146"><strong>Inji Web-1146</strong></a></td><td>Inji Web: In Arabic lang, lang selection option is not properly aligned in in tablet portrait mode</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1144"><strong>Inji Web-1144</strong></a></td><td>Inji Web: Scroll down on share visibility page working as back button</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1143"><strong>Inji Web-1143</strong></a></td><td>Inji Web: On share visibility if click on outside page dropdowns are selected in tablet</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-1142"><strong>Inji Web-1142</strong></a></td><td>Inji Web: Credentials search bar is not properly aligned in tablet view</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-966"><strong>Inji Web-966</strong></a></td><td>Inji Web: For Hindi full stop observed like "।" and also "." in FAQ page</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-965"><strong>Inji Web-965</strong></a></td><td>Inji Web: In some languages in the last FAQ Online Sharing translating to selected lang but not the Embedded VC.</td></tr><tr><td><a href="https://mosip.atlassian.net/browse/INJIWEB-626"><strong>Inji Web-626</strong></a></td><td>Inji Web: Field values in json decoded from CBOR and the values in VC PDF are different</td></tr></tbody></table>

=== _Compatible Modules_

The following table outlines the tested and certified compatibility of _Inji Web 0.11.0_ with other modules.

| Module           | Version                                                          |
| ---------------- | ---------------------------------------------------------------- |
| _eSignet_      | [_v1.4.1_](https://github.com/mosip/esignet/tree/v1.4.1)       |
| _Inji Verify_  | [_v0.10.0_](https://github.com/mosip/inji-verify/tree/v0.10.0) |
| _Inji Certify_ | [_v.0.9.1_](https://github.com/mosip/inji-certify/tree/v0.9.1) |

=== _Repositories Released_

| Repositories           | Tags Released                                                                |
| ---------------------- | ---------------------------------------------------------------------------- |
| _Inji-web_           |  [_v0.11.0_](https://github.com/mosip/inji-web/tree/v0.11.0)               |
| _mimoto_             | [_v0.15.0_](https://github.com/mosip/mimoto/tree/v0.15.0)                  |
| _Inji-config_        | [_v0.4.0_](https://github.com/mosip/inji-config/tree/v0.4.0)               |
| _vc-verifier_        | [_v1.1.0-beta.1_](https://github.com/mosip/vc-verifier/tree/V1.1.0-beta.1) |
| _durian(data share)_ | [_v1.3.0-beta.2_](https://github.com/mosip/durian/tree/1.3.0-beta.2)       |



=== Documentation

_ [_Build and Deployment*](../../build-and-deploy/)
_ [_Feature Documentation*](https://docs.mosip.io/inji/inji-web/functional-overview/features)
_ [_User Guide*](https://docs.mosip.io/inji/inji-web/functional-overview/end-user-guide)
_ [_QA Report*](https://docs.inji.io/inji-wallet/inji-web/inji-web/version-0.11.0/test-report)
_ [_API Documentation*](https://docs.mosip.io/inji/inji-web/technical-overview/backend-services/mimoto-bff)
